/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context"
import type { AuthInfo } from "./../schema/types"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * AuthInfo JSON object. Format: [{"provider": "TWITTER", "id": "id_here"}]
     */
    authinfo<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "AuthInfo";
    /**
     * The javascript `Date` as integer. Type represents date and time as number of milliseconds from start of UNIX epoch.
     */
    timestamp<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Timestamp";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "EmailAddress";
    /**
     * A field whose value conforms to the standard URL format as specified in RFC3986: https://www.ietf.org/rfc/rfc3986.txt.
     */
    url<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "URL";
    /**
     * A field whose value is a hex color code: https://en.wikipedia.org/wiki/Web_colors.
     */
    hex<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "HexColorCode";
    /**
     * TopicPayloadTypes as enum object
     */
    topicPayloadTypes<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "TopicPayloadTypes";
    /**
     * The party object of the invite. Either Server, GroupChat, or User (for friend requests)
     */
    party<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Party";
    /**
     * The `BigInt` scalar type represents non-fractional signed whole numeric values.
     * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
     */
    bigInt<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "BigInt";
    /**
     * The `Byte` scalar type represents byte value as a Buffer
     */
    bytes<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Bytes";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
    /**
     * An arbitrary-precision Decimal type
     */
    decimal<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Decimal";
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Json";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * AuthInfo JSON object. Format: [{"provider": "TWITTER", "id": "id_here"}]
     */
    authinfo<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "AuthInfo";
    /**
     * The javascript `Date` as integer. Type represents date and time as number of milliseconds from start of UNIX epoch.
     */
    timestamp<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Timestamp";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "EmailAddress";
    /**
     * A field whose value conforms to the standard URL format as specified in RFC3986: https://www.ietf.org/rfc/rfc3986.txt.
     */
    url<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "URL";
    /**
     * A field whose value is a hex color code: https://en.wikipedia.org/wiki/Web_colors.
     */
    hex<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "HexColorCode";
    /**
     * TopicPayloadTypes as enum object
     */
    topicPayloadTypes<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "TopicPayloadTypes";
    /**
     * The party object of the invite. Either Server, GroupChat, or User (for friend requests)
     */
    party<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Party";
    /**
     * The `BigInt` scalar type represents non-fractional signed whole numeric values.
     * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
     */
    bigInt<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "BigInt";
    /**
     * The `Byte` scalar type represents byte value as a Buffer
     */
    bytes<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Bytes";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    /**
     * An arbitrary-precision Decimal type
     */
    decimal<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Decimal";
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Json";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DomainCreateInput: { // input type
    description?: string | null; // String
    displayName: string; // String!
    serverId: NexusGenScalars['BigInt']; // BigInt!
    startName?: string | null; // String
    thumbnail?: NexusGenScalars['URL'] | null; // URL
  }
  DomainUpdateInput: { // input type
    description?: string | null; // String
    displayName?: string | null; // String
    order?: number | null; // Int
    startId?: NexusGenScalars['BigInt'] | null; // BigInt
    thumbnail?: NexusGenScalars['URL'] | null; // URL
  }
  InviteCreateInput: { // input type
    expiresAt?: NexusGenScalars['DateTime'] | null; // DateTime
    partyId: NexusGenScalars['BigInt']; // BigInt!
  }
  InviteUpdateInput: { // input type
    expiresAt?: NexusGenScalars['DateTime'] | null; // DateTime
    recipientIds: NexusGenScalars['BigInt'][]; // [BigInt!]!
  }
  RoleCreateInput: { // input type
    admin?: boolean | null; // Boolean
    color: NexusGenScalars['HexColorCode']; // HexColorCode!
    displayName: string; // String!
    domainCrud?: Array<NexusGenEnums['Permission'] | null> | null; // [Permission]
    domainDetails?: Array<NexusGenEnums['DetailPermission'] | null> | null; // [DetailPermission]
    modPerms?: Array<NexusGenEnums['ModPermission'] | null> | null; // [ModPermission]
    owner?: boolean | null; // Boolean
    roomCrud?: Array<NexusGenEnums['Permission'] | null> | null; // [Permission]
    roomDetails?: Array<NexusGenEnums['DetailPermission'] | null> | null; // [DetailPermission]
    serverDetails?: Array<NexusGenEnums['DetailPermission'] | null> | null; // [DetailPermission]
    serverId: NexusGenScalars['BigInt']; // BigInt!
  }
  RoleUpdateInput: { // input type
    admin?: boolean | null; // Boolean
    color?: NexusGenScalars['HexColorCode'] | null; // HexColorCode
    displayName?: string | null; // String
    domainCrud?: Array<NexusGenEnums['Permission'] | null> | null; // [Permission]
    domainDetails?: Array<NexusGenEnums['DetailPermission'] | null> | null; // [DetailPermission]
    modPerms?: Array<NexusGenEnums['ModPermission'] | null> | null; // [ModPermission]
    owner?: boolean | null; // Boolean
    roomCrud?: Array<NexusGenEnums['Permission'] | null> | null; // [Permission]
    roomDetails?: Array<NexusGenEnums['DetailPermission'] | null> | null; // [DetailPermission]
    serverDetails?: Array<NexusGenEnums['DetailPermission'] | null> | null; // [DetailPermission]
  }
  RoomCreateInput: { // input type
    displayName: string; // String!
    domainId: NexusGenScalars['BigInt']; // BigInt!
    thumbnail?: NexusGenScalars['URL'] | null; // URL
  }
  RoomUpdateInput: { // input type
    displayName?: string | null; // String
    thumbnail?: NexusGenScalars['URL'] | null; // URL
  }
  ServerCreateInput: { // input type
    description?: string | null; // String
    displayName: string; // String!
    startName?: string | null; // String
    thumbnail?: NexusGenScalars['URL'] | null; // URL
  }
  ServerUpdateInput: { // input type
    description?: string | null; // String
    displayName?: string | null; // String
    startId?: NexusGenScalars['BigInt'] | null; // BigInt
    thumbnail?: NexusGenScalars['URL'] | null; // URL
  }
  ServerUserCreateInput: { // input type
    avatar?: NexusGenScalars['URL'] | null; // URL
    displayName?: string | null; // String
  }
  ServerUserUpdateInput: { // input type
    avatar?: NexusGenScalars['URL'] | null; // URL
    displayName?: string | null; // String
  }
  UserCreateInput: { // input type
    avatar?: NexusGenScalars['URL'] | null; // URL
    displayName: string; // String!
  }
  UserUpdateInput: { // input type
    avatar?: NexusGenScalars['URL'] | null; // URL
    displayName?: string | null; // String
    lastSeen?: NexusGenScalars['Timestamp'] | null; // Timestamp
  }
}

export interface NexusGenEnums {
  DetailPermission: "DESCRIPTION" | "NAME" | "THUMBNAIL"
  InviteType: "Friend" | "GroupChat" | "Server"
  ModPermission: "BAN" | "DELETE" | "EDIT" | "INVITE" | "MUTE" | "ROLE"
  Permission: "CREATE" | "DELETE" | "READ" | "UPDATE"
  Provider: "EMAIL" | "GITHUB" | "GOOGLE" | "TWITTER"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  AuthInfo: AuthInfo
  BigInt: any
  Bytes: any
  DateTime: any
  Decimal: any
  EmailAddress: string
  HexColorCode: string
  Json: any
  Timestamp: number
  TopicPayloadTypes: any
  URL: string
}

export interface NexusGenObjects {
  Account: { // root type
    authInfo?: NexusGenScalars['AuthInfo'] | null; // AuthInfo
    authProvider?: NexusGenEnums['Provider'] | null; // Provider
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    disabled: boolean; // Boolean!
    email?: NexusGenScalars['EmailAddress'] | null; // EmailAddress
    id: string; // ID!
    password?: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Domain: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    displayName: string; // String!
    id: NexusGenScalars['BigInt']; // BigInt!
    order: number; // Int!
    serverId: NexusGenScalars['BigInt']; // BigInt!
    startId: NexusGenScalars['BigInt']; // BigInt!
    thumbnail?: NexusGenScalars['URL'] | null; // URL
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  GroupChat: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    displayName: string; // String!
    id: NexusGenScalars['BigInt']; // BigInt!
    ownerId: NexusGenScalars['BigInt']; // BigInt!
    thumbnail?: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Invite: { // root type
    expiresAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: NexusGenScalars['BigInt']; // BigInt!
    ownerId: NexusGenScalars['BigInt']; // BigInt!
    partyId: NexusGenScalars['BigInt']; // BigInt!
    type: NexusGenEnums['InviteType']; // InviteType!
  }
  Mutation: {};
  Query: {};
  Role: { // root type
    admin: boolean; // Boolean!
    color: NexusGenScalars['HexColorCode']; // HexColorCode!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    displayName: string; // String!
    domainCrud: NexusGenEnums['Permission'][]; // [Permission!]!
    domainDetails: NexusGenEnums['DetailPermission'][]; // [DetailPermission!]!
    id: NexusGenScalars['BigInt']; // BigInt!
    modPerms: NexusGenEnums['ModPermission'][]; // [ModPermission!]!
    order: number; // Int!
    owner: boolean; // Boolean!
    roomCrud: NexusGenEnums['Permission'][]; // [Permission!]!
    roomDetails: NexusGenEnums['DetailPermission'][]; // [DetailPermission!]!
    serverDetails: NexusGenEnums['DetailPermission'][]; // [DetailPermission!]!
    serverId: NexusGenScalars['BigInt']; // BigInt!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Room: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    displayName: string; // String!
    domainId: NexusGenScalars['BigInt']; // BigInt!
    id: NexusGenScalars['BigInt']; // BigInt!
    thumbnail?: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Server: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    displayName: string; // String!
    id: NexusGenScalars['BigInt']; // BigInt!
    ownerId: NexusGenScalars['BigInt']; // BigInt!
    startId: NexusGenScalars['BigInt']; // BigInt!
    thumbnail?: NexusGenScalars['URL'] | null; // URL
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  ServerUser: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    displayName?: string | null; // String
    id: NexusGenScalars['BigInt']; // BigInt!
    serverId: NexusGenScalars['BigInt']; // BigInt!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    userId: NexusGenScalars['BigInt']; // BigInt!
  }
  Subscription: {};
  User: { // root type
    accountId: string; // String!
    avatar?: NexusGenScalars['URL'] | null; // URL
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    disabled: boolean; // Boolean!
    displayName: string; // String!
    id: NexusGenScalars['BigInt']; // BigInt!
    lastSeen: NexusGenScalars['Timestamp']; // Timestamp!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
  Party: NexusGenRootTypes['GroupChat'] | NexusGenRootTypes['Server'] | NexusGenRootTypes['User'];
}

export type NexusGenRootTypes = NexusGenObjects & NexusGenUnions

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Account: { // field return type
    authInfo: NexusGenScalars['AuthInfo'] | null; // AuthInfo
    authProvider: NexusGenEnums['Provider'] | null; // Provider
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    disabled: boolean; // Boolean!
    email: NexusGenScalars['EmailAddress'] | null; // EmailAddress
    id: string; // ID!
    password: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  Domain: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    displayName: string; // String!
    id: NexusGenScalars['BigInt']; // BigInt!
    order: number; // Int!
    rooms: NexusGenRootTypes['Room'][]; // [Room!]!
    server: NexusGenRootTypes['Server']; // Server!
    serverId: NexusGenScalars['BigInt']; // BigInt!
    start: NexusGenRootTypes['Room']; // Room!
    startId: NexusGenScalars['BigInt']; // BigInt!
    thumbnail: NexusGenScalars['URL'] | null; // URL
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  GroupChat: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    displayName: string; // String!
    id: NexusGenScalars['BigInt']; // BigInt!
    owner: NexusGenRootTypes['User']; // User!
    ownerId: NexusGenScalars['BigInt']; // BigInt!
    thumbnail: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  Invite: { // field return type
    expiresAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: NexusGenScalars['BigInt']; // BigInt!
    owner: NexusGenRootTypes['User']; // User!
    ownerId: NexusGenScalars['BigInt']; // BigInt!
    party: NexusGenRootTypes['Party'] | null; // Party
    partyId: NexusGenScalars['BigInt']; // BigInt!
    type: NexusGenEnums['InviteType']; // InviteType!
  }
  Mutation: { // field return type
    acceptInvite: NexusGenRootTypes['Invite'] | null; // Invite
    createDomain: NexusGenRootTypes['Domain'] | null; // Domain
    createFriendInvite: NexusGenRootTypes['Invite'] | null; // Invite
    createGroupChatInvite: NexusGenRootTypes['Invite'] | null; // Invite
    createRoom: NexusGenRootTypes['Room'] | null; // Room
    createServer: NexusGenRootTypes['Server'] | null; // Server
    createServerInvite: NexusGenRootTypes['Invite'] | null; // Invite
    createUser: NexusGenRootTypes['User'] | null; // User
    deleteInvite: NexusGenRootTypes['Invite'] | null; // Invite
    updateDomain: NexusGenRootTypes['Domain'] | null; // Domain
    updateRoom: NexusGenRootTypes['Room'] | null; // Room
    updateServer: NexusGenRootTypes['Server'] | null; // Server
    updateServerUser: NexusGenRootTypes['ServerUser'] | null; // ServerUser
    updateUser: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    domainById: NexusGenRootTypes['Domain'] | null; // Domain
    getInviteById: NexusGenRootTypes['Invite'] | null; // Invite
    getInvitesByPartyId: Array<NexusGenRootTypes['Invite'] | null> | null; // [Invite]
    roleById: NexusGenRootTypes['Role'] | null; // Role
    roomById: NexusGenRootTypes['Room'] | null; // Room
    serverById: NexusGenRootTypes['Server'] | null; // Server
    serverUserById: NexusGenRootTypes['ServerUser'] | null; // ServerUser
    serverUserByServerId: NexusGenRootTypes['ServerUser'] | null; // ServerUser
    topicPayloadTypes: NexusGenScalars['TopicPayloadTypes'] | null; // TopicPayloadTypes
    userById: NexusGenRootTypes['User'] | null; // User
    userByName: NexusGenRootTypes['User'] | null; // User
    userCommonality: NexusGenScalars['Json'] | null; // Json
  }
  Role: { // field return type
    admin: boolean; // Boolean!
    color: NexusGenScalars['HexColorCode']; // HexColorCode!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    displayName: string; // String!
    domainCrud: NexusGenEnums['Permission'][]; // [Permission!]!
    domainDetails: NexusGenEnums['DetailPermission'][]; // [DetailPermission!]!
    id: NexusGenScalars['BigInt']; // BigInt!
    members: NexusGenRootTypes['ServerUser'][]; // [ServerUser!]!
    modPerms: NexusGenEnums['ModPermission'][]; // [ModPermission!]!
    order: number; // Int!
    owner: boolean; // Boolean!
    roomCrud: NexusGenEnums['Permission'][]; // [Permission!]!
    roomDetails: NexusGenEnums['DetailPermission'][]; // [DetailPermission!]!
    server: NexusGenRootTypes['Server']; // Server!
    serverDetails: NexusGenEnums['DetailPermission'][]; // [DetailPermission!]!
    serverId: NexusGenScalars['BigInt']; // BigInt!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Room: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    displayName: string; // String!
    domain: NexusGenRootTypes['Domain']; // Domain!
    domainId: NexusGenScalars['BigInt']; // BigInt!
    id: NexusGenScalars['BigInt']; // BigInt!
    thumbnail: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Server: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    displayName: string; // String!
    domains: NexusGenRootTypes['Domain'][]; // [Domain!]!
    id: NexusGenScalars['BigInt']; // BigInt!
    owner: NexusGenRootTypes['User']; // User!
    ownerId: NexusGenScalars['BigInt']; // BigInt!
    start: NexusGenRootTypes['Domain']; // Domain!
    startId: NexusGenScalars['BigInt']; // BigInt!
    thumbnail: NexusGenScalars['URL'] | null; // URL
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  ServerUser: { // field return type
    avatar: NexusGenScalars['URL'] | null; // URL
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    displayName: string | null; // String
    id: NexusGenScalars['BigInt']; // BigInt!
    roles: NexusGenRootTypes['Role'][]; // [Role!]!
    server: NexusGenRootTypes['Server']; // Server!
    serverId: NexusGenScalars['BigInt']; // BigInt!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    user: NexusGenRootTypes['User']; // User!
    userId: NexusGenScalars['BigInt']; // BigInt!
  }
  Subscription: { // field return type
    domainSnapshot: NexusGenRootTypes['Domain'] | null; // Domain
    inviteSnapshot: NexusGenRootTypes['Invite'] | null; // Invite
    roomSnapshot: NexusGenRootTypes['Room'] | null; // Room
    serverSnapshot: NexusGenRootTypes['Server'] | null; // Server
    serverUserSnapshot: NexusGenRootTypes['ServerUser'] | null; // ServerUser
    userSnapshot: NexusGenRootTypes['User'] | null; // User
  }
  User: { // field return type
    account: NexusGenRootTypes['Account']; // Account!
    accountId: string; // String!
    avatar: NexusGenScalars['URL'] | null; // URL
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    disabled: boolean; // Boolean!
    displayName: string; // String!
    groupChats: NexusGenRootTypes['GroupChat'][]; // [GroupChat!]!
    id: NexusGenScalars['BigInt']; // BigInt!
    lastSeen: NexusGenScalars['Timestamp']; // Timestamp!
    ownedServers: NexusGenRootTypes['Server'][]; // [Server!]!
    servers: NexusGenRootTypes['Server'][]; // [Server!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenFieldTypeNames {
  Account: { // field return type name
    authInfo: 'AuthInfo'
    authProvider: 'Provider'
    createdAt: 'DateTime'
    disabled: 'Boolean'
    email: 'EmailAddress'
    id: 'ID'
    password: 'String'
    updatedAt: 'DateTime'
    users: 'User'
  }
  Domain: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    displayName: 'String'
    id: 'BigInt'
    order: 'Int'
    rooms: 'Room'
    server: 'Server'
    serverId: 'BigInt'
    start: 'Room'
    startId: 'BigInt'
    thumbnail: 'URL'
    updatedAt: 'DateTime'
  }
  GroupChat: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    displayName: 'String'
    id: 'BigInt'
    owner: 'User'
    ownerId: 'BigInt'
    thumbnail: 'String'
    updatedAt: 'DateTime'
    users: 'User'
  }
  Invite: { // field return type name
    expiresAt: 'DateTime'
    id: 'BigInt'
    owner: 'User'
    ownerId: 'BigInt'
    party: 'Party'
    partyId: 'BigInt'
    type: 'InviteType'
  }
  Mutation: { // field return type name
    acceptInvite: 'Invite'
    createDomain: 'Domain'
    createFriendInvite: 'Invite'
    createGroupChatInvite: 'Invite'
    createRoom: 'Room'
    createServer: 'Server'
    createServerInvite: 'Invite'
    createUser: 'User'
    deleteInvite: 'Invite'
    updateDomain: 'Domain'
    updateRoom: 'Room'
    updateServer: 'Server'
    updateServerUser: 'ServerUser'
    updateUser: 'User'
  }
  Query: { // field return type name
    domainById: 'Domain'
    getInviteById: 'Invite'
    getInvitesByPartyId: 'Invite'
    roleById: 'Role'
    roomById: 'Room'
    serverById: 'Server'
    serverUserById: 'ServerUser'
    serverUserByServerId: 'ServerUser'
    topicPayloadTypes: 'TopicPayloadTypes'
    userById: 'User'
    userByName: 'User'
    userCommonality: 'Json'
  }
  Role: { // field return type name
    admin: 'Boolean'
    color: 'HexColorCode'
    createdAt: 'DateTime'
    displayName: 'String'
    domainCrud: 'Permission'
    domainDetails: 'DetailPermission'
    id: 'BigInt'
    members: 'ServerUser'
    modPerms: 'ModPermission'
    order: 'Int'
    owner: 'Boolean'
    roomCrud: 'Permission'
    roomDetails: 'DetailPermission'
    server: 'Server'
    serverDetails: 'DetailPermission'
    serverId: 'BigInt'
    updatedAt: 'DateTime'
  }
  Room: { // field return type name
    createdAt: 'DateTime'
    displayName: 'String'
    domain: 'Domain'
    domainId: 'BigInt'
    id: 'BigInt'
    thumbnail: 'String'
    updatedAt: 'DateTime'
  }
  Server: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    displayName: 'String'
    domains: 'Domain'
    id: 'BigInt'
    owner: 'User'
    ownerId: 'BigInt'
    start: 'Domain'
    startId: 'BigInt'
    thumbnail: 'URL'
    updatedAt: 'DateTime'
    users: 'User'
  }
  ServerUser: { // field return type name
    avatar: 'URL'
    createdAt: 'DateTime'
    displayName: 'String'
    id: 'BigInt'
    roles: 'Role'
    server: 'Server'
    serverId: 'BigInt'
    updatedAt: 'DateTime'
    user: 'User'
    userId: 'BigInt'
  }
  Subscription: { // field return type name
    domainSnapshot: 'Domain'
    inviteSnapshot: 'Invite'
    roomSnapshot: 'Room'
    serverSnapshot: 'Server'
    serverUserSnapshot: 'ServerUser'
    userSnapshot: 'User'
  }
  User: { // field return type name
    account: 'Account'
    accountId: 'String'
    avatar: 'URL'
    createdAt: 'DateTime'
    disabled: 'Boolean'
    displayName: 'String'
    groupChats: 'GroupChat'
    id: 'BigInt'
    lastSeen: 'Timestamp'
    ownedServers: 'Server'
    servers: 'Server'
    updatedAt: 'DateTime'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    acceptInvite: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    createDomain: { // args
      data: NexusGenInputs['DomainCreateInput']; // DomainCreateInput!
    }
    createFriendInvite: { // args
      uid: NexusGenScalars['BigInt']; // BigInt!
    }
    createGroupChatInvite: { // args
      data: NexusGenInputs['InviteCreateInput']; // InviteCreateInput!
    }
    createRoom: { // args
      data: NexusGenInputs['RoomCreateInput']; // RoomCreateInput!
    }
    createServer: { // args
      data: NexusGenInputs['ServerCreateInput']; // ServerCreateInput!
    }
    createServerInvite: { // args
      data: NexusGenInputs['InviteCreateInput']; // InviteCreateInput!
    }
    createUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
    deleteInvite: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    updateDomain: { // args
      data: NexusGenInputs['DomainUpdateInput']; // DomainUpdateInput!
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    updateRoom: { // args
      data: NexusGenInputs['RoomUpdateInput']; // RoomUpdateInput!
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    updateServer: { // args
      data: NexusGenInputs['ServerUpdateInput']; // ServerUpdateInput!
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    updateServerUser: { // args
      data: NexusGenInputs['ServerUserUpdateInput']; // ServerUserUpdateInput!
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    updateUser: { // args
      data: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
    }
  }
  Query: {
    domainById: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    getInviteById: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    getInvitesByPartyId: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
      type: NexusGenEnums['InviteType']; // InviteType!
    }
    roleById: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    roomById: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    serverById: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    serverUserById: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    serverUserByServerId: { // args
      sId: NexusGenScalars['BigInt']; // BigInt!
      uId: NexusGenScalars['BigInt']; // BigInt!
    }
    userById: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    userByName: { // args
      displayName: string; // String!
    }
    userCommonality: { // args
      uid: NexusGenScalars['BigInt']; // BigInt!
    }
  }
  Subscription: {
    domainSnapshot: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    inviteSnapshot: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    roomSnapshot: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    serverSnapshot: { // args
      id: NexusGenScalars['BigInt']; // BigInt!
    }
    serverUserSnapshot: { // args
      sid?: NexusGenScalars['BigInt'] | null; // BigInt
      uid: NexusGenScalars['BigInt']; // BigInt!
    }
    userSnapshot: { // args
      uid: NexusGenScalars['BigInt']; // BigInt!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  Party: "GroupChat" | "Server" | "User"
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = keyof NexusGenUnions;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    resolveType: false
    __typename: false
    isTypeOf: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}