/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../util/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Date type, serialized as milliseconds since epoch
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
    /**
     * BigInt type
     */
    bigint<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "BigInt";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Date type, serialized as milliseconds since epoch
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
    /**
     * BigInt type
     */
    bigint<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "BigInt";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  BigInt: any
  Date: any
}

export interface NexusGenObjects {
  Query: {};
  User: { // root type
    avatar?: string | null; // String
    createdAt: NexusGenScalars['Date']; // Date!
    disabled?: boolean | null; // Boolean
    displayName: string; // String!
    friends?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    groupchats?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    id: NexusGenScalars['BigInt']; // BigInt!
    lastSeen?: NexusGenScalars['Date'] | null; // Date
    servers?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
  }
}

export interface NexusGenInterfaces {
  Node: NexusGenRootTypes['User'];
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Query: { // field return type
    userById: NexusGenRootTypes['User'] | null; // User
    userByName: NexusGenRootTypes['User'] | null; // User
  }
  User: { // field return type
    avatar: string | null; // String
    createdAt: NexusGenScalars['Date']; // Date!
    disabled: boolean | null; // Boolean
    displayName: string; // String!
    friends: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    groupchats: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    id: NexusGenScalars['BigInt']; // BigInt!
    lastSeen: NexusGenScalars['Date'] | null; // Date
    servers: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
  }
  Node: { // field return type
    id: NexusGenScalars['BigInt']; // BigInt!
  }
}

export interface NexusGenFieldTypeNames {
  Query: { // field return type name
    userById: 'User'
    userByName: 'User'
  }
  User: { // field return type name
    avatar: 'String'
    createdAt: 'Date'
    disabled: 'Boolean'
    displayName: 'String'
    friends: 'BigInt'
    groupchats: 'BigInt'
    id: 'BigInt'
    lastSeen: 'Date'
    servers: 'BigInt'
  }
  Node: { // field return type name
    id: 'BigInt'
  }
}

export interface NexusGenArgTypes {
  Query: {
    userById: { // args
      id: string; // ID!
    }
    userByName: { // args
      displayName: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  Node: "User"
}

export interface NexusGenTypeInterfaces {
  User: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    resolveType: false
    __typename: false
    isTypeOf: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}